version: '3.9'

services:
  fastapi:
    container_name: film_search
    image: film_search:v2.0
    build:
      context: .
      dockerfile: fast_api/docker/Dockerfile
    env_file:
      - ./envs/.fastapi.env
    depends_on:
      - es
      - redis
  es:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis_data:/data
  nginx:
    container_name: nginx
    image: nginx:1.21.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    depends_on:
      - fastapi
  tests:
    container_name: test_fastapi
    image: test_fastapi:v1.0
    build:
      context: .
      dockerfile: tests/docker/Dockerfile
    env_file:
      - ./envs/.fastapi.env
    depends_on:
      - es
      - redis
volumes:
  elastic_data:
  redis_data: